language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-text
